# amfs_tm/configs/clean_config.yaml
cleaning_steps:
  - raw_data_filename_pattern: axa_avr_{snapshot}.txt
    processed_data_filename_pattern: axa_avr_{snapshot}.csv
    data_source: BM
    cleaning_type: standard

  - raw_data_filename_pattern: cifsumm_{snapshot}.txt
    processed_data_filename_pattern: cifsumm_{snapshot}.csv
    data_source: BM
    cleaning_type: balance

  - raw_data_filename_pattern: phsumm_{snapshot}.txt
    processed_data_filename_pattern: PHSUMM_{snapshot}.csv
    data_source: BM
    cleaning_type: balance

  - raw_data_filename_pattern: cif_acct_mapping_{snapshot}.txt
    processed_data_filename_pattern: cif_acct_mapping_{snapshot}.csv
    data_source: BM
    cleaning_type: standard

  - raw_data_filename_pattern: cc_type_cnt_{snapshot}.txt
    processed_data_filename_pattern: cc_type_cnt_{snapshot}.csv
    data_source: BM
    cleaning_type: standard

  - raw_data_filename_pattern: axa_cust_demo_{snapshot}.txt
    processed_data_filename_pattern: axa_cust_demo_{snapshot}.csv
    data_source: BM
    cleaning_type: custdemo

  - raw_data_filename_pattern: dc_type_cnt_{snapshot}.txt
    processed_data_filename_pattern: dc_type_cnt_{snapshot}.csv
    data_source: BM
    cleaning_type: standard

  - raw_data_filename_pattern: axa_cust_cd_{snapshot}.txt
    processed_data_filename_pattern: axa_cust_cd_{snapshot}.csv
    data_source: BM
    cleaning_type: standard

  - raw_data_filename_pattern: debitcard_trx_edc_{snapshot}.txt
    processed_data_filename_pattern: debitcard_trx_edc_{snapshot}.txt
    data_source: BM
    cleaning_type: trxdebit_edc

  - raw_data_filename_pattern: axa_tran_net_{snapshot}.txt
    processed_data_filename_pattern: axa_tran_net_{snapshot}.csv
    data_source: BM
    cleaning_type: trxnet

  - raw_data_filename_pattern: trx_outflow_{snapshot}.txt
    processed_data_filename_pattern: trx_outflow_{snapshot}.csv
    data_source: BM
    cleaning_type: standard

  - raw_data_filename_pattern: trx_outflow_payment_purchase_{snapshot}.txt
    processed_data_filename_pattern: trx_outflow_payment_purchase_{snapshot}.csv
    data_source: BM
    cleaning_type: standard

  - raw_data_filename_pattern: axa_tran_allper_cd_{snapshot}.txt
    processed_data_filename_pattern: axa_tran_allper_cd_{snapshot}.csv
    data_source: BM
    cleaning_type: standard

  - raw_data_filename_pattern: axa_tran_allper_db_{snapshot}.txt
    processed_data_filename_pattern: axa_tran_allper_db_{snapshot}.csv
    data_source: BM
    cleaning_type: standard

  - raw_data_filename_pattern: cust_zipcode_mapping_{snapshot}.txt
    processed_data_filename_pattern: cust_zipcode_mapping_{snapshot}.csv
    data_source: BM
    cleaning_type: standard

  - raw_data_filename_pattern: ALL_STATUS_{snapshot}.csv
    processed_data_filename_pattern: ALL_STATUS_{snapshot}.csv
    data_source: AMFS
    cleaning_type: standard

  - raw_data_filename_pattern: call_tracking_savings_{snapshot}.csv
    processed_data_filename_pattern: call_tracking_savings_{snapshot}.csv
    data_source: AMFS
    cleaning_type: standard