[bankavr]
is_job_run = 0
job_functions = create
job_type = feature

[creditcard_type]
is_job_run = 0
job_functions = create
job_type = feature

[debitcard_type]
is_job_run = 0
job_functions = create
job_type = feature

[custdemo]
is_job_run = 0
job_functions = create
job_type = feature

[bankph]
is_job_run = 0
job_functions = create,create_loan,create_saving_account
job_type = feature

[balance]
is_job_run = 0
job_functions = create_clean,create_raw,create,create_deduct,create_real
job_type = feature

[maxtrxdate]
is_job_run = 0
job_functions = create
job_type = feature

[trxdebit_edc]
is_job_run = 0
#job_functions = create,create_lag
job_functions = create
job_type = feature

[trxnet]
is_job_run = 0
#job_functions = create,create_lag
job_functions = create
job_type = feature

[trxoutflow]
is_job_run = 0
#job_functions = create,create_lag
job_functions = create
job_type = feature

[trxoutflow_payment]
is_job_run = 0
#job_functions = create,create_lag
job_functions = create
job_type = feature

[trxper]
is_job_run = 0
job_functions = create
job_type = feature

[zipcode]
is_job_run = 0
job_functions = accumulate,create
job_type = feature

[tso]
is_job_run = 0
job_functions = create
job_type = feature

[flag]
is_job_run = 1
job_functions = create
job_type = flag

[fpf]
is_job_run = 0
job_functions = create
job_type = feature

