# amfs_tm/configs/main_config.yaml
PATHS:
  # The absolute Volume path to your Schema
  base_path: /Volumes/main/amfs_telemarketing_new_acquisition

  # Volume names as shown in your Databricks screenshot
  raw_dir_prefix: 01_raw
  processed_dir_prefix: 02_processed
  features_dir_prefix: 03_features

  # Directory names inside the Volumes
  bm_features_subdir: BM_features
  axa_features_subdir: AXA_Features
  matrix_output_dir_prefix: 04_matrix