[conf]
#id = camp{DIL}
#input = CAMP_{campaign}/01_filters/camp{DIL}_cifno_filtered_{snapshot}.csv
input = 03_features/BM_features/cif_with_flag_{snapshot}_active_complete_{snapshot}.csv
merge_output = 04_matrix/final_matrix_{snapshot}.csv
dummified_output = 04_matrix/final_matrix_{snapshot}_dummified.csv
sep = |
running_mode = merge

# models
[build]
value = 

[contact]
value = 

[convert]
value = 

[fpf]
value = 

[axa_avr_{snapshot}_feat.h5]
name = avr
sep = nan
addon_cols = nan
file_format = %%Y%%m
use_cols = nan
key = CIFNO
addon = nan

[bal_{snapshot}_feat.h5]
name = bal
sep = nan
addon_cols = nan
file_format = %%y%%m
use_cols = nan
key = CIFNO
addon = nan

[bal_deduct_{snapshot}.csv]
name = bal_deduct
sep = |
addon_cols = nan
file_format = %%Y%%m
use_cols = nan
key = CIFNO
addon = nan

[loan_diff_{snapshot}.csv]
name = loan_diff
sep = |
addon_cols = nan
file_format = %%Y%%m
use_cols = CIFNO, loan_to_debit, loan_recent_inc_flag, loan_recent_inc_count, tot_loan_t-1, tot_loan_t-2, tot_loan_delta_t_t-1, tot_loan_delta_t_t-2
key = CIFNO
addon = nan

[Saving_Acct_{snapshot}.csv]
name = saving_acct
sep = |
addon_cols = nan
file_format = %%Y%%m
use_cols = CIFNO, TOT_UNDEBIT_SAVING, delta_undebit_saving, delta_micro_saving, only_undebit_acct_flag, only_micro_flag, ratio_undebit_saving, ratio_micro_saving, no_saving_acct_flag
key = CIFNO
addon = nan

[bal_loan_feat_{snapshot}.csv]
name = bal_loan
sep = |
addon_cols = nan
file_format = %%y%%m
use_cols = CIFNO, AVG_lm_loan, MED_lm_loan, MX_lm_loan, MN_lm_loan, QT1_lm_loan, QT3_lm_loan, D20_lm_loan, EOM_lm_loan, delta_max_min_bal_lm_loan, MED_lm2_loan, QT1_lm2_loan, QT3_lm2_loan, MED_lm3_loan, QT1_lm3_loan, QT3_lm3_loan, max_bal_3mth_loan, max_bal_6mth_loan, min_bal_3mth_loan, min_bal_6mth_loan, max_delta_bal_3mth_loan, max_delta_bal_6mth_loan, avg_lm2_loan, avg_lm3_loan, avg_bal_3mth_loan, avg_bal_6mth_loan, eom_3mth_loan, eom_6mth_loan, d20_3mth_loan, delta_avg_bal_t1_t2_loan, delta_avg_bal_t2_t3_loan, delta_avg_bal_t3_t4_loan
key = CIFNO
addon = nan

[axa_cust_demo_clean_{snapshot}.csv]
name = cust_demo
sep = |
addon_cols = nan
file_format = %%Y%%m
use_cols = nan
key = cusno
addon = nan

[cc_type_cnt_{snapshot}_feat.h5]
name = cc_type_cnt
sep = nan
addon_cols = nb_alop,nb_classic, nb_gold, nb_platinum, nb_signature
file_format = %%Y%%m
use_cols = nan
key = cifno
addon = _cc

[dc_type_cnt_{snapshot}_feat.h5]
name = dc_type_cnt
sep = nan
addon_cols = nb_prioritas, nb_silver, nb_gold, nb_platinum, nb_others
file_format = %%Y%%m
use_cols = nan
key = cifno
addon = _dc

[debitcard_trx_edc_{snapshot}_feat.h5]
name = dc_trx_edc
sep = nan
addon_cols = all
file_format = %%Y%%m
use_cols = nan
key = cifno
addon = _db_edc

[debitcard_trx_edc_{snapshot}_lag_feat.h5]
name = dc_trx_edc_lag
sep = nan
addon_cols = all
file_format = %%Y%%m
use_cols = cifno, sum_sv_lm3_db_edc, sum_freq_lm3_db_edc, sum_sv_lm6_db_edc, sum_freq_lm6_db_edc, sv_lm_lm3_diff_db_edc, sv_lm3_lm6_diff_db_edc, freq_lm_lm3_diff_db_edc, freq_lm3_lm6_diff_db_edc, max_sv_lm3_db_edc, min_sv_lm3_db_edc, mean_sv_lm3_db_edc, max_sv_lm6_db_edc, min_sv_lm6_db_edc, mean_sv_lm6_db_edc, max_freq_lm3_db_edc, min_freq_lm3_db_edc, mean_freq_lm3_db_edc, max_freq_lm6_db_edc, min_freq_lm6_db_edc, mean_freq_lm6_db_edc
key = cifno
addon = _db_edc

[maxtrxdate_cddb_{snapshot}_feat.h5]
name = maxtrxdate_cddb
sep = nan
addon_cols = nan
file_format = %%Y%%m
use_cols = cifno, maxcd_amt, maxcd_num, maxcd_num_day, maxcd_num_uni_weekday, maxcd_day_1_10, maxcd_day_11_20, maxcd_day_21_up, maxdb_amt, maxdb_num, maxdb_num_day, maxdb_num_uni_weekday, maxdb_day_1_10, maxdb_day_11_20, maxdb_day_21_up
key = cifno
addon = nan

[PHSUMM_{snapshot}_feat.h5]
name = PHSUMM
sep = nan
addon_cols = all
file_format = %%Y%%m
use_cols = nan
key = CIFNO
addon = _bank_ph

[trxnet_{snapshot}_feat.h5]
name = trxnet_kon
sep = nan
addon_cols = all
file_format = %%Y%%m
use_cols = nan
key = cifno
addon = _trxnet

[trxnet_{snapshot}_lag_feat.h5]
name = trxnet_lag_bangsat
sep = nan
addon_cols = all
file_format = %%Y%%m
use_cols = cifno, sum_db_lm3_trxnet, sum_cd_lm3_trxnet, sum_db_lm6_trxnet, sum_cd_lm6_trxnet, db_lm_lm3_diff_trxnet, db_lm3_lm6_diff_trxnet, cd_lm_lm3_diff_trxnet, cd_lm3_lm6_diff_trxnet, max_db_lm3_trxnet, min_db_lm3_trxnet, mean_db_lm3_trxnet, max_db_lm6_trxnet, min_db_lm6_trxnet, mean_db_lm6_trxnet, max_cd_lm3_trxnet, min_cd_lm3_trxnet, mean_cd_lm3_trxnet, max_cd_lm6_trxnet, min_cd_lm6_trxnet, mean_cd_lm6_trxnet
key = cifno
addon = _trxnet

[trxout_{snapshot}_feat.h5]
name = trxout
sep = nan
addon_cols = all
file_format = %%Y%%m
use_cols = nan
key = cifno_pengirim
addon = _trxout

[trxout_{snapshot}_lag_feat.h5]
name = trxout_lag
sep = nan
addon_cols = all
file_format = %%Y%%m
use_cols = cifno_pengirim, trxout_lm3_trxout, trxout_lm6_trxout, trxout_lm_lm3_diff_trxout, trxout_lm3_lm6_diff_trxout, max_trxout_lm3_trxout, min_trxout_lm3_trxout, mean_trxout_lm3_trxout, max_trxout_lm6_trxout, min_trxout_lm6_trxout, mean_trxout_lm6_trxout
key = cifno_pengirim
addon = _trxout

[trxout_purchase_{snapshot}_feat.h5]
name = trxout_purchase
sep = nan
addon_cols = all
file_format = %%Y%%m
use_cols = nan
key = customer_no
addon = _trxout

[trxout_purchase_{snapshot}_lag_feat.h5]
name = trxout_purchase_lag
sep = nan
addon_cols = all
file_format = %%Y%%m
use_cols = customer_no, purchase_amt_lm3_trxout, purchase_amt_lm6_trxout, purchase_amt_lm_lm3_diff_trxout, purchase_amt_lm3_lm6_diff_trxout, max_purchase_amt_lm3_trxout, min_purchase_amt_lm3_trxout, mean_purchase_amt_lm3_trxout, max_purchase_amt_lm6_trxout, min_purchase_amt_lm6_trxout, mean_purchase_amt_lm6_trxout
key = customer_no
addon = _trxout

[trxper_{snapshot}_feat.h5]
name = trxper
sep = nan
addon_cols = all
file_format = %%Y%%m
use_cols = nan
key = cifno
addon = _trxper

[timezone_ggp_pop_feature_{snapshot}.csv]
name = geo_feat
sep = ,
addon_cols = nan
file_format = %%y%%m
use_cols = nan
key = cifno
addon = nan

