 # amfs_tm/configs/model_config.yaml

# amfs_tm/configs/model_config.yaml

training_settings:
  test_size: 0.2
  random_state: 42
  target_col: "target"
  # Add the specific invalid columns found in your error log here
  features_to_drop: 
    - cifno
    - target
    - date_org
    - mxdt
    - mndt
    - yymm
    - weekday_mxdt_x
    - weekday_mndt_x
    - gp1pdt_x
    - gp1pdt_y
    - sfstopn
    - slstopn
    - dfstopn
    - dlstopn
    - gfstopn
    - glstopn
    - cfstopn
    - clstopn
    - weekday_mxdt_y
    - weekday_mndt_y

# XGBoost Hyperparameters
model_params:
  n_estimators: 200
  max_depth: 5
  learning_rate: 0.05
  objective: "binary:logistic"
  eval_metric: "auc"
  # Use 'hist' for faster training on Databricks clusters
  tree_method: "hist" 
  scale_pos_weight: 1 # Increase if conversion rate is very low (e.g., 10 or 20)